version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
#  pre_build:
#    commands:
#      - yarn install
artifacts:
  files:
    - '**/*'
  base-directory: './'
  post_build:
    commands:
      - npm run start
