version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install --global yarn
  pre_build:
    commands:
      - yarn install
artifacts:
  files:
    - '**/*'
  base-directory: './'
#  post_build:
#    commands:
#      - aws s3 sync ./build s3://uat-ebill-frontend
