version: 0.2
env:
  variables:
    ECR_REPO: 215596008133.dkr.ecr.ap-southeast-1.amazonaws.com/getjihuoma
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t getjihuoma . --file Dockerfile
      - echo "Tagging Docker image for ECR.."
      - docker tag getjihuoma ${ECR_REPO}:01
      - echo "Logging into ECR.."
      - $(aws ecr get-login --no-include-email)
      - echo "Pushing Docker image to ECR.."
      - docker push ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Done."
